services:

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: cctv
      WATCHTOWER_POLL_INTERVAL: 3600

  dns-server:
    image: docker.io/technitium/dns-server:latest
    container_name: dns-server
    hostname: dns-server
    restart: unless-stopped
    network_mode: host
    environment:
      - DNS_SERVER_DOMAIN=dns-server
      - DNS_SERVER_ADMIN_PASSWORD=${DNS_ADMIN_PASSWORD}
      - DNS_SERVER_WEB_SERVICE_ENABLE_HTTPS=true
      - DNS_SERVER_WEB_SERVICE_USE_SELF_SIGNED_CERT=true
      - DNS_SERVER_WEB_SERVICE_HTTPS_PORT=53443
      - DNS_SERVER_RECURSION=AllowOnlyForPrivateNetworks
      - DNS_SERVER_FORWARDERS=https://security.cloudflare-dns.com/dns-query
      - DNS_SERVER_FORWARDER_PROTOCOL=Https
      - DNS_SERVER_ENABLE_BLOCKING=true
      - DNS_SERVER_ALLOW_TXT_BLOCKING_REPORT=true
      - DNS_SERVER_BLOCK_LIST_URLS=https://abp.markridgwell.com/hosts.txt,https://abp.markridgwell.com/adblock.txt,https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/doh-vpn-proxy-bypass.txt,https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/multi.txt,https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/hoster.txt
      - DNS_SERVER_LOG_USING_LOCAL_TIME=true
    volumes:
      - /data/technitium/config:/etc/dns
      - /data/technitium/logs:/var/log/technitium/dns
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
